version: '3.8'

services:
  backend:
    build: .
    command: sh -c "sleep 5 && ./main"
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432