version: '3.8'

services:
  backend:
    build: .
    command: sh -c "sleep 10 && ./main"
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=studybuddy
    ports:
      - 5432:5432