version: '3.8'

services:
  backend:
    build: .
    command: sh -c "sleep 10 && migrate -path ./schema -database 'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$DB_HOST:$DB_PORT/$POSTGRES_DB?sslmode=disable' up && ./main"
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432